[terminal]
shell = { program = "/opt/homebrew/bin/yash" }

[general]
live_config_reload = true

[font]
size = 16

[font.normal]
family = "ComicShannsMono Nerd Font"

[font.bold]
family = "ComicShannsMono Nerd Font"

[font.italic]
family = "ComicShannsMono Nerd Font"

[font.bold_italic]
family = "ComicShannsMono Nerd Font"
